### ISSUE TITLE
Unable to decrypt request

### ISSUE THREAD

**Issue by wnabil** [paytabscom/paytabs-cordova#3]
Getting error 'Unable to decrypt request' when trying to pay with Credit card on Android platform
``` "cordova": "^10.0.0",
"cordova-android": "^9.1.0",
"cordova-plugin-ionic-webview": "^5.0.0",
"com.paytabs.cordova.plugin": "^1.2.2",
"@angular/compiler-cli": "^8.1.0",

<preference name="Hostname" value="localhost" />
<preference name="Scheme" value="https" /> tested with http, same error
<preference name="AndroidXEnabled" value="true" />

Android V6.0.1
Samsung Galaxy Note 4 (SM-N910C)
```

The form opens, I put all the details, credit card info and billing info then error appears after clicking on pay button

**Comment by wnabil** [comment]
Same error in iOS

**Comment by MuhamedAdly** [comment]
Please make sure you are using the Mobile SDK keys, if you don't have it added to your profile, contact the customer support team cs@paytabs.com to add it to your profile.

**Comment by wnabil** [comment]
It was an issue with the client id in the config, closing as not related to the plugin
