### ISSUE TITLE
"plugin not installed" error even after install the plugin

### ISSUE THREAD

**Issue by shanthan25** [paytabscom/paytabs-cordova#5]
"plugin not installed" error showing even after install the plugin. I imported the plugin in the app.module.ts file also.

I have used following version:
"@awesome-cordova-plugins/paytabs": "^5.39.1",
"com.paytabs.cordova.plugin": "^1.2.3",

        ionic info
        
        Ionic:
        
           Ionic CLI                     : 6.18.1 (C:\Users\Mutants\AppData\Roaming\npm\node_modules\@ionic\cli)
           Ionic Framework               : @ionic/angular 5.6.0-dev.202012031726.dc9faa6
           @angular-devkit/build-angular : 0.1000.8
           @angular-devkit/schematics    : 10.0.8
           @angular/cli                  : 10.0.8
           @ionic/angular-toolkit        : 2.3.3
        
        Cordova:
        
           Cordova CLI       : 10.0.0
           Cordova Platforms : android 9.1.0
           Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 9 other plugins)
        
        Utility:
        
           cordova-res (update available: 0.15.4) : 0.15.3
           native-run (update available: 1.5.0)   : 1.4.0
        
        System:
        
           Android SDK Tools : 26.1.1 (C:\Users\Mutants\Android\Sdk)
           NodeJS            : v14.17.3 (C:\Program Files\nodejs\node.exe)
           npm               : 6.14.13
           OS                : Windows 10

**Comment by Gautammer** [comment]
Same problem!

**Comment by shanthan25** [comment]
> Same problem!
try "cordova.plugins.CordovaPaymentPlugin.startCardPayment(configuration)" instead of "this.paytabs.startCardPayment(configuration)". it is working for me

    cordova.plugins.CordovaPaymentPlugin.startCardPayment(configuration, (result) => {
          if (result.status === 'success') {
              const transactionDetails = result.data;
              console.log('responseCode:' + transactionDetails.paymentResult.responseCode);
              console.log('transactionTime:' + transactionDetails.paymentResult.transactionTime);
              console.log('responseMessage:' + transactionDetails.paymentResult.responseMessage);
              console.log('transactionReference:' + transactionDetails.transactionReference);
              console.log('token:' + transactionDetails.token);
          } else if (result.status === 'error') {
          } else if (result.status === 'event') {
              // Handle events here.
          }
      }, (error) => {
          console.log(error);
          alert(error);
      });

**Comment by Gautammer** [comment]
> > Same problem!
> > try "cordova.plugins.CordovaPaymentPlugin.startCardPayment(configuration)" instead of "this.paytabs.startCardPayment(configuration)". it is working for me
> 
> ```
> cordova.plugins.CordovaPaymentPlugin.startCardPayment(configuration, (result) => {
>       if (result.status === 'success') {
>           const transactionDetails = result.data;
>           console.log('responseCode:' + transactionDetails.paymentResult.responseCode);
>           console.log('transactionTime:' + transactionDetails.paymentResult.transactionTime);
>           console.log('responseMessage:' + transactionDetails.paymentResult.responseMessage);
>           console.log('transactionReference:' + transactionDetails.transactionReference);
>           console.log('token:' + transactionDetails.token);
>       } else if (result.status === 'error') {
>       } else if (result.status === 'event') {
>           // Handle events here.
>       }
>   }, (error) => {
>       console.log(error);
>       alert(error);
>   });
> ```

Thanks
cordova.plugins.CordovaPaymentPlugin

Getting undefined!
Should i import anything?

**Comment by shanthan25** [comment]
@Gautammer  need to declare cordova like below.

     declare let cordova: any;

**Comment by Gautammer** [comment]
Thank you it fixed the issue!
but after opening native payment page of paytabs and filling card detail form i am getting 
**Request must be in JSON format with content type application/json** 

any solution for this?
i am using android 9.1.0

**Comment by Gautammer** [comment]
**Fixed,
it was my mistake :)
I was using API keys instead if SDK keys in app.**
