### ISSUE TITLE
Error related to dependency Dependency: androidx.core:core-ktx:1.7.0.

### ISSUE THREAD

**Issue by haniyasin** [paytabscom/paytabs-cordova#7]
The minCompileSdk (31) specified in a
dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
is greater than this module's compileSdkVersion (android-30).
Dependency: androidx.core:core-ktx:1.7.0.
AAR metadata file: C:\Users\haniy\.gradle\caches\transforms-3\a238884f7bb586be0b19d770543c7b11\transformed\jetified-core-ktx-1.7.0\META-INF\com\android\build\gradle\aar-metadata.properties.
-----------------------------------------------------------------------------------------------------------------------------------
Package.json:

"author": "Apache Cordova Team",
  "license": "Apache-2.0",
  "devDependencies": {
    "com.paytabs.cordova.plugin": "^1.2.3",
    "cordova-android": "^10.1.2"
  },
  "cordova": {
    "platforms": [
      "android"
    ],
    "plugins": {
      "com.paytabs.cordova.plugin": {}
    }
  }
---------------------------------------------------------------------------------------------------------------------------------

**Comment by KhaledAlramam** [comment]
Make sure your compileSdk and targetSdk are both 31 or higher inside your android/app/build.gradle file
